name: ๐ Bug Report - ุชูุฑูุฑ ุฎุทุฃ
description: ุงูุฅุจูุงุบ ุนู ุฎุทุฃ ุฃู ูุดููุฉ ูู ุงูุชุทุจูู
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ุดูุฑุงู ูู ุนูู ุงูุฅุจูุงุบ ุนู ูุฐุง ุงูุฎุทุฃ! ๐
        ูุฑุฌู ููุก ุงููููุฐุฌ ุงูุชุงูู ุจุฃูุจุฑ ูุฏุฑ ูู ุงูุชูุงุตูู ููุณุงุนุฏุชูุง ูู ุญู ุงููุดููุฉ.

  - type: textarea
    id: bug-description
    attributes:
      label: ๐ ูุตู ุงูุฎุทุฃ
      description: ูุตู ูุงุถุญ ููุฎุชุตุฑ ููุฎุทุฃ ุงูุฐู ูุงุฌูุชู
      placeholder: ูุซุงู: ุนูุฏ ุงูุถุบุท ุนูู ุฒุฑ "ุฅุถุงูุฉ ูููุฉ"ุ ูุง ูุญุฏุซ ุดูุก ููุง ุชุธูุฑ ุฃู ุฑุณุงูุฉ ุฎุทุฃ
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: ๐ ุฎุทูุงุช ุฅุนุงุฏุฉ ุฅูุชุงุฌ ุงูุฎุทุฃ
      description: ุฎุทูุงุช ููุตูุฉ ูุฅุนุงุฏุฉ ุฅูุชุงุฌ ุงููุดููุฉ
      placeholder: |
        1. ุงุฐูุจ ุฅูู ุตูุญุฉ ุงูููุงู
        2. ุงุถุบุท ุนูู ุฒุฑ "ุฅุถุงูุฉ ูููุฉ"
        3. ุงููุฃ ุงููููุฐุฌ
        4. ุงุถุบุท ุนูู "ุญูุธ"
        5. ูุงุญุธ ุฃู ุงููููุฉ ูู ุชูุถุงู
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: โ ุงูุณููู ุงููุชููุน
      description: ูุตู ููุง ูุงู ูุฌุจ ุฃู ูุญุฏุซ
      placeholder: ูุฌุจ ุฃู ุชูุถุงู ุงููููุฉ ุงูุฌุฏูุฏุฉ ุฅูู ุงููุงุฆูุฉ ูุชุธูุฑ ุฑุณุงูุฉ ูุฌุงุญ
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: โ ุงูุณููู ุงููุนูู
      description: ูุตู ููุง ุญุฏุซ ุจุงููุนู
      placeholder: ูุง ูุญุฏุซ ุดูุกุ ุงููููุฉ ูุง ุชูุถุงู ููุง ุชุธูุฑ ุฃู ุฑุณุงูุฉ
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: ๐ ุงููุชุตูุญ
      description: ุฃู ูุชุตูุญ ุชุณุชุฎุฏูุ
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - ุฃุฎุฑู
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: ๐ ุฅุตุฏุงุฑ ุงููุชุตูุญ
      description: ูุง ูู ุฅุตุฏุงุฑ ุงููุชุตูุญุ
      placeholder: ูุซุงู: Chrome 120.0.6099.109
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: ๐ป ูุธุงู ุงูุชุดุบูู
      description: ุฃู ูุธุงู ุชุดุบูู ุชุณุชุฎุฏูุ
      options:
        - Windows 11
        - Windows 10
        - macOS
        - Ubuntu
        - Linux (ุฃุฎุฑู)
        - ุฃุฎุฑู
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: ๐ฑ ุฅุตุฏุงุฑ ุงูุชุทุจูู
      description: ูุง ูู ุฅุตุฏุงุฑ Y0 Task Managerุ
      placeholder: ูุซุงู: v1.0.0
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: ๐ ุฃุฎุทุงุก ูุญุฏุฉ ุงูุชุญูู
      description: |
        ุงูุชุญ Developer Tools (F12) ูุงูุณุฎ ุฃู ุฃุฎุทุงุก ูู Console
        ```
        ุถุน ุงูุฃุฎุทุงุก ููุง
        ```
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: ๐ธ ููุทุงุช ุงูุดุงุดุฉ
      description: |
        ุฅุฐุง ุฃูููุ ุฃุถู ููุทุงุช ุดุงุดุฉ ูุชูุถูุญ ุงููุดููุฉ
        ููููู ุณุญุจ ูุฅููุงุช ุงูุตูุฑ ููุง

  - type: textarea
    id: additional-context
    attributes:
      label: ๐ ูุนูููุงุช ุฅุถุงููุฉ
      description: ุฃู ูุนูููุงุช ุฃุฎุฑู ูุฏ ุชุณุงุนุฏ ูู ุญู ุงููุดููุฉ
      placeholder: |
        - ูู ุงููุดููุฉ ุชุญุฏุซ ุฏุงุฆูุงู ุฃู ุฃุญูุงูุงูุ
        - ูู ุฌุฑุจุช ุญููู ุฃุฎุฑูุ
        - ูุชู ุจุฏุฃุช ุงููุดููุฉุ

  - type: checkboxes
    id: terms
    attributes:
      label: โ ุงูุชุฃููุฏุงุช
      description: ูุฑุฌู ุงูุชุฃูุฏ ูู ุงูููุงุท ุงูุชุงููุฉ
      options:
        - label: ุจุญุซุช ูู Issues ุงูููุฌูุฏุฉ ููู ุฃุฌุฏ ูุดููุฉ ูุดุงุจูุฉ
          required: true
        - label: ุฌุฑุจุช ุฅุนุงุฏุฉ ุชุญููู ุงูุตูุญุฉ ููุง ุฒุงูุช ุงููุดููุฉ ููุฌูุฏุฉ
          required: true
        - label: ุงููุนูููุงุช ุงูููุฏูุฉ ุฏูููุฉ ููุงููุฉ
          required: true
